spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yi120214
    url: jdbc:mysql://localhost:3306/cdf?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  config-location: classpath:mybatis/mybatis.xml
server:
  servlet:
    context-path: /cdf





